#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent
# Spec: 001-a-simple-unique-profile-settings-screen

set -e

echo "========================================"
echo "Starting Development Environment"
echo "SSS Flutter App - Profile Screen Feature"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Project directory
PROJECT_DIR="/Users/yeswanthvarmakanumuri/Downloads/SSS/sss"

cd "$PROJECT_DIR"

echo ""
echo "Checking Flutter environment..."

# Check Flutter is installed
if ! command -v flutter &> /dev/null; then
    echo -e "${RED}Flutter is not installed or not in PATH${NC}"
    exit 1
fi

echo -e "${GREEN}Flutter found${NC}"

# Get Flutter version
flutter --version

echo ""
echo "========================================"
echo "Running Flutter Doctor"
echo "========================================"

flutter doctor

echo ""
echo "========================================"
echo "Getting Dependencies"
echo "========================================"

flutter pub get

echo ""
echo "========================================"
echo "Running Static Analysis"
echo "========================================"

flutter analyze || true

echo ""
echo "========================================"
echo "Running Existing Tests"
echo "========================================"

flutter test || true

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "To run the app:"
echo "  flutter run                    # Default device"
echo "  flutter run -d ios             # iOS Simulator"
echo "  flutter run -d chrome          # Chrome (web)"
echo ""
echo "To run tests:"
echo "  flutter test"
echo ""
echo "To analyze code:"
echo "  flutter analyze"
echo ""
echo "Spec Directory:"
echo "  .auto-claude/specs/001-a-simple-unique-profile-settings-screen/"
echo ""
echo "Implementation Plan:"
echo "  cat .auto-claude/specs/001-a-simple-unique-profile-settings-screen/implementation_plan.json"
echo ""
