import 'dart:convert';

/// NFC Tag Data Model with System Identifier and Deep Link Support
///
/// This model represents the data structure associated with NFC tags
/// generated by this system. It includes:
/// - a stable ID used for deep links (sss://nfc/[id])
/// - a system identifier to verify NFC tags created by this app
/// - optional category/title and visual identifier metadata
/// - NFC tag unique identifier (tagId)
class NFCTagData {
  /// Deep link URL scheme host segment used by this app.
  /// NFC tags use sss://nfc/<id> to distinguish from QR codes (sss://qr/<id>)
  static const String deepLinkScheme = 'sss';
  static const String deepLinkHost = 'nfc';

  /// System identifier constant to verify NFC tags from this system
  static const String systemId = 'SSS_NFC_SYSTEM_v1';

  /// NFC format version
  static const String version = '1.0.0';

  /// Stable identifier for this NFC entry (used in deep links)
  final String id;

  /// User-provided content/data
  final String data;

  /// Creation timestamp in ISO 8601 format
  final String timestamp;

  /// NFC tag unique identifier (from the physical tag)
  final String? tagId;

  /// Optional custom identifier (icon/letter) for visual differentiation
  final String? customIdentifier;

  /// Optional category/title, used for display
  final String? category;

  /// Constructor
  NFCTagData({
    required this.id,
    required this.data,
    required this.timestamp,
    this.tagId,
    this.customIdentifier,
    this.category,
  });

  /// Create NFCTagData from JSON
  factory NFCTagData.fromJson(Map<String, dynamic> json) {
    return NFCTagData(
      id: json['id'] as String,
      data: json['data'] as String,
      timestamp: json['timestamp'] as String,
      tagId: json['tagId'] as String?,
      customIdentifier: json['customIdentifier'] as String?,
      category: json['category'] as String?,
    );
  }

  /// Convert NFCTagData to JSON
  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'systemId': systemId,
      'version': version,
      'data': data,
      'timestamp': timestamp,
      if (tagId != null) 'tagId': tagId,
      if (customIdentifier != null) 'customIdentifier': customIdentifier,
      if (category != null) 'category': category,
    };
  }

  /// Convert NFCTagData to JSON string for NFC encoding
  String toJsonString() {
    return jsonEncode(toJson());
  }

  /// Verify if a JSON string contains the system identifier
  static bool verifySystemNFC(String jsonString) {
    try {
      final json = jsonDecode(jsonString) as Map<String, dynamic>;
      return json['systemId'] == systemId;
    } catch (e) {
      return false;
    }
  }

  /// Create NFCTagData with current timestamp
  factory NFCTagData.create({
    String? id,
    required String data,
    String? tagId,
    String? customIdentifier,
    String? category,
  }) {
    return NFCTagData(
      id: id ?? _generateId(),
      data: data,
      timestamp: DateTime.now().toIso8601String(),
      tagId: tagId,
      customIdentifier: customIdentifier,
      category: category,
    );
  }

  /// Generate a reasonably unique ID without external dependencies.
  static String _generateId() {
    final timestamp = DateTime.now().microsecondsSinceEpoch.toString();
    final randomComponent = (timestamp.hashCode & 0xFFFFFF).toRadixString(16);
    return '$timestamp-$randomComponent';
  }

  /// Build a deep link URL of the form: sss://nfc/[id]
  String buildDeepLink() {
    return '$deepLinkScheme://$deepLinkHost/$id';
  }

  /// Check whether a string looks like a deep link generated by this system.
  /// Accepts both sss://nfc/<id> and legacy sss://qr/<id> formats.
  static bool isSystemDeepLink(String value) {
    return value.startsWith('$deepLinkScheme://$deepLinkHost/') ||
        value.startsWith('$deepLinkScheme://qr/');
  }

  /// Attempt to extract the NFC id from a deep link URL.
  /// Accepts both sss://nfc/<id> and legacy sss://qr/<id> formats.
  static String? extractIdFromDeepLink(String value) {
    if (!isSystemDeepLink(value)) {
      return null;
    }
    try {
      final uri = Uri.parse(value);
      if (uri.scheme != deepLinkScheme) return null;
      if (uri.host != deepLinkHost && uri.host != 'qr') return null;
      // Expect path like '/<id>'
      final segments = uri.pathSegments;
      if (segments.isEmpty) return null;
      return segments.first;
    } catch (_) {
      return null;
    }
  }
}




