import 'dart:convert';

/// QR Data Model with System Identifier and Deep Link Support
///
/// This model represents the data structure associated with QR codes
/// generated by this system. It includes:
/// - a stable ID used for deep links (`sss://qr/<id>`)
/// - a system identifier to verify QR codes created by this app
/// - optional category/title and visual identifier metadata.
class QRData {
  /// Deep link URL scheme host segment used by this app.
  static const String deepLinkScheme = 'sss';
  static const String deepLinkHost = 'qr';

  /// System identifier constant to verify QR codes from this system
  static const String systemId = 'SSS_SYSTEM_v1';

  /// QR format version
  static const String version = '1.0.0';

  /// Stable identifier for this QR entry (used in deep links)
  final String id;

  /// User-provided content/data
  final String data;

  /// Creation timestamp in ISO 8601 format
  final String timestamp;

  /// Optional custom identifier (icon/letter) for visual differentiation
  final String? customIdentifier;

  /// Optional category/title, used for display/printing
  final String? category;

  /// Constructor
  QRData({
    required this.id,
    required this.data,
    required this.timestamp,
    this.customIdentifier,
    this.category,
  });

  /// Create QRData from JSON
  factory QRData.fromJson(Map<String, dynamic> json) {
    return QRData(
      id: json['id'] as String,
      data: json['data'] as String,
      timestamp: json['timestamp'] as String,
      customIdentifier: json['customIdentifier'] as String?,
      category: json['category'] as String?,
    );
  }

  /// Convert QRData to JSON
  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'systemId': systemId,
      'version': version,
      'data': data,
      'timestamp': timestamp,
      if (customIdentifier != null) 'customIdentifier': customIdentifier,
      if (category != null) 'category': category,
    };
  }

  /// Convert QRData to JSON string for QR encoding
  String toJsonString() {
    return jsonEncode(toJson());
  }

  /// Verify if a JSON string contains the system identifier
  static bool verifySystemQR(String jsonString) {
    try {
      final json = jsonDecode(jsonString) as Map<String, dynamic>;
      return json['systemId'] == systemId;
    } catch (e) {
      return false;
    }
  }

  /// Create QRData with current timestamp
  factory QRData.create({
    String? id,
    required String data,
    String? customIdentifier,
    String? category,
  }) {
    return QRData(
      id: id ?? _generateId(),
      data: data,
      timestamp: DateTime.now().toIso8601String(),
      customIdentifier: customIdentifier,
      category: category,
    );
  }

  /// Generate a reasonably unique ID without external dependencies.
  static String _generateId() {
    final timestamp = DateTime.now().microsecondsSinceEpoch.toString();
    final randomComponent = (timestamp.hashCode & 0xFFFFFF).toRadixString(16);
    return '$timestamp-$randomComponent';
  }

  /// Build a deep link URL of the form: sss://qr/<id>
  String buildDeepLink() {
    return '$deepLinkScheme://$deepLinkHost/$id';
  }

  /// Check whether a string looks like a deep link generated by this system.
  static bool isSystemDeepLink(String value) {
    return value.startsWith('$deepLinkScheme://$deepLinkHost/');
  }

  /// Attempt to extract the QR id from a deep link URL.
  static String? extractIdFromDeepLink(String value) {
    if (!isSystemDeepLink(value)) {
      return null;
    }
    try {
      final uri = Uri.parse(value);
      if (uri.scheme != deepLinkScheme) return null;
      if (uri.host != deepLinkHost) return null;
      // Expect path like '/<id>'
      final segments = uri.pathSegments;
      if (segments.isEmpty) return null;
      return segments.first;
    } catch (_) {
      return null;
    }
  }
}

