import 'dart:convert';

/// QR Data Model with System Identifier
/// 
/// This model represents the data structure encoded in QR codes
/// generated by this system. It includes a system identifier to
/// verify that the QR code was created by this application.
class QRData {
  /// System identifier constant to verify QR codes from this system
  static const String systemId = 'SSS_SYSTEM_v1';

  /// QR format version
  static const String version = '1.0.0';

  /// User-provided content/data
  final String data;

  /// Creation timestamp in ISO 8601 format
  final String timestamp;

  /// Optional custom identifier (icon/letter) for visual differentiation
  final String? customIdentifier;

  /// Constructor
  QRData({
    required this.data,
    required this.timestamp,
    this.customIdentifier,
  });

  /// Create QRData from JSON
  factory QRData.fromJson(Map<String, dynamic> json) {
    return QRData(
      data: json['data'] as String,
      timestamp: json['timestamp'] as String,
      customIdentifier: json['customIdentifier'] as String?,
    );
  }

  /// Convert QRData to JSON
  Map<String, dynamic> toJson() {
    return {
      'systemId': systemId,
      'version': version,
      'data': data,
      'timestamp': timestamp,
      if (customIdentifier != null) 'customIdentifier': customIdentifier,
    };
  }

  /// Convert QRData to JSON string for QR encoding
  String toJsonString() {
    return jsonEncode(toJson());
  }

  /// Verify if a JSON string contains the system identifier
  static bool verifySystemQR(String jsonString) {
    try {
      final json = jsonDecode(jsonString) as Map<String, dynamic>;
      return json['systemId'] == systemId;
    } catch (e) {
      return false;
    }
  }

  /// Create QRData with current timestamp
  factory QRData.create({
    required String data,
    String? customIdentifier,
  }) {
    return QRData(
      data: data,
      timestamp: DateTime.now().toIso8601String(),
      customIdentifier: customIdentifier,
    );
  }
}

