import 'package:flutter/material.dart';
import '../models/qr_data.dart';
import '../services/qr_service.dart';

/// POC Screen for testing QR code generation and export features
class QRPOCScreen extends StatefulWidget {
  const QRPOCScreen({super.key});

  @override
  State<QRPOCScreen> createState() => _QRPOCScreenState();
}

class _QRPOCScreenState extends State<QRPOCScreen> {
  final TextEditingController _dataController = TextEditingController();
  final TextEditingController _letterController = TextEditingController();
  final GlobalKey _qrKey = GlobalKey();
  
  String _currentData = '';
  String? _embeddedLetter;
  bool _isGenerating = false;
  String? _statusMessage;
  bool _isSuccess = false;

  @override
  void initState() {
    super.initState();
    _dataController.text = 'Sample QR Code Data';
    _currentData = _dataController.text;
  }

  @override
  void dispose() {
    _dataController.dispose();
    _letterController.dispose();
    super.dispose();
  }

  void _generateQR() {
    setState(() {
      _currentData = _dataController.text.trim();
      _embeddedLetter = _letterController.text.trim().isEmpty 
          ? null 
          : _letterController.text.trim();
      _statusMessage = null;
    });
  }

  Future<void> _exportAsPNG() async {
    if (_currentData.isEmpty) {
      _showMessage('Please enter data first', false);
      return;
    }

    setState(() {
      _isGenerating = true;
      _statusMessage = null;
    });

    try {
      // Capture the QR widget as image
      final imageBytes = await QRService.captureWidgetToImage(
        repaintBoundaryKey: _qrKey,
      );

      if (imageBytes == null) {
        _showMessage('Failed to capture QR code image', false);
        return;
      }

      final fileName = 'qr_code_${DateTime.now().millisecondsSinceEpoch}.png';
      final filePath = await QRService.exportAsPNG(
        imageBytes: imageBytes,
        fileName: fileName,
      );

      if (filePath != null) {
        _showMessage('PNG exported successfully: $fileName', true);
      } else {
        _showMessage('Failed to export PNG', false);
      }
    } catch (e) {
      _showMessage('Error: $e', false);
    } finally {
      setState(() {
        _isGenerating = false;
      });
    }
  }

  Future<void> _exportAsPDF() async {
    if (_currentData.isEmpty) {
      _showMessage('Please enter data first', false);
      return;
    }

    setState(() {
      _isGenerating = true;
      _statusMessage = null;
    });

    try {
      // Capture the QR widget as image
      final imageBytes = await QRService.captureWidgetToImage(
        repaintBoundaryKey: _qrKey,
      );

      if (imageBytes == null) {
        _showMessage('Failed to capture QR code image', false);
        return;
      }

      final fileName = 'qr_code_${DateTime.now().millisecondsSinceEpoch}.pdf';
      final filePath = await QRService.exportAsPDF(
        imageBytes: imageBytes,
        fileName: fileName,
        data: _currentData,
        title: 'QR Code',
        description: 'Generated by SSS System',
      );

      if (filePath != null) {
        _showMessage('PDF exported successfully: $fileName', true);
      } else {
        _showMessage('Failed to export PDF', false);
      }
    } catch (e) {
      _showMessage('Error: $e', false);
    } finally {
      setState(() {
        _isGenerating = false;
      });
    }
  }

  Future<void> _shareFile(String extension) async {
    if (_currentData.isEmpty) {
      _showMessage('Please enter data first', false);
      return;
    }

    setState(() {
      _isGenerating = true;
      _statusMessage = null;
    });

    try {
      // Capture the QR widget as image
      final imageBytes = await QRService.captureWidgetToImage(
        repaintBoundaryKey: _qrKey,
      );

      if (imageBytes == null) {
        _showMessage('Failed to capture QR code image', false);
        return;
      }

      final timestamp = DateTime.now().millisecondsSinceEpoch;
      String? filePath;

      if (extension == 'png') {
        final fileName = 'qr_code_$timestamp.png';
        filePath = await QRService.exportAsPNG(
          imageBytes: imageBytes,
          fileName: fileName,
        );
      } else {
        final fileName = 'qr_code_$timestamp.pdf';
        filePath = await QRService.exportAsPDF(
          imageBytes: imageBytes,
          fileName: fileName,
          data: _currentData,
          title: 'QR Code',
          description: 'Generated by SSS System',
        );
      }

      if (filePath != null) {
        final success = await QRService.shareFile(
          filePath: filePath,
          subject: 'QR Code from SSS',
          text: 'QR Code generated by SSS System',
        );

        if (success) {
          _showMessage('File shared successfully', true);
        } else {
          _showMessage('Failed to share file', false);
        }
      } else {
        _showMessage('Failed to create file for sharing', false);
      }
    } catch (e) {
      _showMessage('Error: $e', false);
    } finally {
      setState(() {
        _isGenerating = false;
      });
    }
  }

  void _verifyQR() {
    if (_currentData.isEmpty) {
      _showMessage('Please generate a QR code first', false);
      return;
    }

    final qrDataString = QRService.generateQRData(data: _currentData);
    final isValid = QRService.verifySystemQR(qrDataString);

    _showMessage(
      isValid 
          ? '✓ QR Code verified - Created by SSS System'
          : '✗ QR Code verification failed',
      isValid,
    );
  }

  void _showMessage(String message, bool isSuccess) {
    setState(() {
      _statusMessage = message;
      _isSuccess = isSuccess;
    });

    // Clear message after 3 seconds
    Future.delayed(const Duration(seconds: 3), () {
      if (mounted) {
        setState(() {
          _statusMessage = null;
        });
      }
    });
  }

  Widget _buildQRWidget() {
    if (_currentData.isEmpty) {
      return Container(
        width: 200,
        height: 200,
        decoration: BoxDecoration(
          color: Colors.grey[200],
          borderRadius: BorderRadius.circular(8),
        ),
        child: const Center(
          child: Text(
            'Enter data to generate QR code',
            textAlign: TextAlign.center,
            style: TextStyle(color: Colors.grey),
          ),
        ),
      );
    }

    Widget qrWidget;
    if (_embeddedLetter != null && _embeddedLetter!.isNotEmpty) {
      qrWidget = QRService.createQRWidgetWithLetter(
        data: _currentData,
        embeddedLetter: _embeddedLetter!,
        size: 200,
      );
    } else {
      qrWidget = QRService.createQRWidget(
        data: _currentData,
        size: 200,
      );
    }

    return RepaintBoundary(
      key: _qrKey,
      child: qrWidget,
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('QR Code POC'),
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(16.0),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.stretch,
          children: [
            // Data input
            TextField(
              controller: _dataController,
              decoration: const InputDecoration(
                labelText: 'QR Code Data',
                hintText: 'Enter data to encode',
                border: OutlineInputBorder(),
              ),
              maxLines: 3,
            ),
            const SizedBox(height: 16),

            // Embedded letter input
            TextField(
              controller: _letterController,
              decoration: const InputDecoration(
                labelText: 'Embedded Letter (Optional)',
                hintText: 'Enter a single letter or character',
                border: OutlineInputBorder(),
                helperText: 'Add a letter/character in the center for uniqueness',
              ),
              maxLength: 1,
              textCapitalization: TextCapitalization.characters,
            ),
            const SizedBox(height: 16),

            // Generate button
            ElevatedButton.icon(
              onPressed: _isGenerating ? null : _generateQR,
              icon: const Icon(Icons.qr_code),
              label: const Text('Generate QR Code'),
              style: ElevatedButton.styleFrom(
                padding: const EdgeInsets.symmetric(vertical: 16),
              ),
            ),
            const SizedBox(height: 24),

            // QR Code preview
            Center(
              child: _buildQRWidget(),
            ),
            const SizedBox(height: 24),

            // Status message
            if (_statusMessage != null)
              Container(
                padding: const EdgeInsets.all(12),
                margin: const EdgeInsets.only(bottom: 16),
                decoration: BoxDecoration(
                  color: _isSuccess ? Colors.green[100] : Colors.red[100],
                  borderRadius: BorderRadius.circular(8),
                  border: Border.all(
                    color: _isSuccess ? Colors.green : Colors.red,
                  ),
                ),
                child: Text(
                  _statusMessage!,
                  style: TextStyle(
                    color: _isSuccess ? Colors.green[900] : Colors.red[900],
                  ),
                ),
              ),

            // Action buttons
            Wrap(
              spacing: 8,
              runSpacing: 8,
              alignment: WrapAlignment.center,
              children: [
                ElevatedButton.icon(
                  onPressed: _isGenerating || _currentData.isEmpty
                      ? null
                      : _exportAsPNG,
                  icon: const Icon(Icons.image),
                  label: const Text('Export PNG'),
                ),
                ElevatedButton.icon(
                  onPressed: _isGenerating || _currentData.isEmpty
                      ? null
                      : _exportAsPDF,
                  icon: const Icon(Icons.picture_as_pdf),
                  label: const Text('Export PDF'),
                ),
                ElevatedButton.icon(
                  onPressed: _isGenerating || _currentData.isEmpty
                      ? null
                      : () => _shareFile('png'),
                  icon: const Icon(Icons.share),
                  label: const Text('Share PNG'),
                ),
                ElevatedButton.icon(
                  onPressed: _isGenerating || _currentData.isEmpty
                      ? null
                      : () => _shareFile('pdf'),
                  icon: const Icon(Icons.share),
                  label: const Text('Share PDF'),
                ),
                ElevatedButton.icon(
                  onPressed: _isGenerating || _currentData.isEmpty
                      ? null
                      : _verifyQR,
                  icon: const Icon(Icons.verified),
                  label: const Text('Verify QR'),
                ),
              ],
            ),

            if (_isGenerating)
              const Padding(
                padding: EdgeInsets.all(16.0),
                child: Center(
                  child: CircularProgressIndicator(),
                ),
              ),

            const SizedBox(height: 24),

            // Info section
            Card(
              child: Padding(
                padding: const EdgeInsets.all(16.0),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    const Text(
                      'System Information',
                      style: TextStyle(
                        fontSize: 16,
                        fontWeight: FontWeight.bold,
                      ),
                    ),
                    const SizedBox(height: 8),
                    Text('System ID: ${QRData.systemId}'),
                    Text('Version: ${QRData.version}'),
                    const SizedBox(height: 8),
                    const Text(
                      'All QR codes generated by this system include a system identifier that can be verified when scanned.',
                      style: TextStyle(fontSize: 12, color: Colors.grey),
                    ),
                  ],
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }
}

